### ISSUE TITLE
--no-hot is broken

### ISSUE THREAD

**Issue by zenflow** [webpack-contrib/webpack-serve#22]
* Operating System: 10
* Node Version: 8.9.4
* NPM Version: 5.6.0
* webpack Version: 3.11.0
* webpack-serve Version: 0.1.4

This issue is for a:

- [X] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve sandbox/webpack.config.js --no-hot
```

##### webpack.config.js

<details>

```js
const path = require('path')
const ModuleScopePlugin = require('react-dev-utils/ModuleScopePlugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const { ProvidePlugin, NamedModulesPlugin } = require('webpack')
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin')
const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin')

const appSrc = path.resolve('./lib')
const appPackageJson = path.resolve('./package.json')
const appNodeModules = path.resolve('./node_modules')

module.exports = {
  devtool: 'cheap-module-source-map',
  entry: [require.resolve('./app')],
  output: {
    pathinfo: true, // Add /* filename */ comments to generated require()s in the output.
    filename: 'bundle.js', // This does not produce a real file. It's just a virtual path.
    publicPath: '/', // This is the URL that app is served from.
    devtoolModuleFilenameTemplate(info) {
      // Point sourcemap entries to original disk location (format as URL on Windows)
      return path.resolve(info.absoluteResourcePath).replace(/\\/g, '/')
    },
  },
  resolve: {
    modules: ['node_modules'], // .concat(process.env.NODE_PATH.split(path.delimiter).filter(Boolean)),
    extensions: ['.js'],
    plugins: [
      new ModuleScopePlugin(appSrc, [appPackageJson]), // Prevents users from importing files from outside of src/ (or node_modules/).
    ],
  },
  module: {
    strictExportPresence: true,
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: require.resolve('babel-loader'),
        options: {},
      },
    ],
  },
  plugins: [
    new ProvidePlugin({ React: 'react' }),
    new HtmlWebpackPlugin({ inject: true }), // Generates the `index.html` file
    new NamedModulesPlugin(), // Add module names to factory func
    // Watcher doesn't work well if you mistype casing in a path so we use
    // a plugin that prints an error when you attempt to do this.
    // See https://github.com/facebookincubator/create-react-app/issues/240
    new CaseSensitivePathsPlugin(),
    // If you require a missing module and then `npm install` it, you still have
    // to restart the development server for Webpack to discover it. This plugin
    // makes the discovery automatic so you don't have to restart.
    // See https://github.com/facebookincubator/create-react-app/issues/186
    new WatchMissingNodeModulesPlugin(appNodeModules),
  ],
}
```

</details>

### Expected Behavior
Expected process not to crash

### Actual Behavior
Throws:
```
TypeError: Cannot create property 'host' on boolean 'false'
    at resolve.then (C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\webpack-serve\lib\options.js:119:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

### How Do We Reproduce?

Try using the `--no-hot` flag in the CLI

**Comment by shellscape** [comment]
Thanks for the issue 🍺  I'll have a look.

As an aside, we're prepping a minor release (we're still unstable and beneath a 1.0.0 version) that removes webpack v3 support. Are you able to upgrade to webpack v4?

**Comment by zenflow** [comment]
@shellscape Already have a PR almost ready!

**Comment by zenflow** [comment]
> As an aside, we're prepping a minor release (we're still unstable and beneath a 1.0.0 version) that removes webpack v3 support. Are you able to upgrade to webpack v4?

Will give it a try!

**Comment by zenflow** [comment]
@shellscape Nope, Webpack 4 doesn't work for me

```js
> sweetalert2-react-content@0.0.2 dev:sandbox C:\Users\Matt\Documents\dev\sweetalert2-react-content
> webpack-serve sandbox/webpack.config.js --no-hot --no-reload --open

(node:2560) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
ℹ ｢hot｣: webpack: Compiling...
(node:2560) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
ℹ ｢hot｣: WebSocket Server Listening at localhost:8081
ℹ ｢serve｣: Project is running at http://localhost:8080
ℹ ｢serve｣: Server URI copied to clipboard
ℹ ｢wdm｣: wait until bundle finished:
ℹ ｢wdm｣: wait until bundle finished: /
C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\html-webpack-plugin\lib\compiler.js:81
        var outputName = compilation.mainTemplate.applyPluginsWaterfall('asset-path', outputOptions.filename, {
                                                  ^

TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
    at C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\html-webpack-plugin\lib\compiler.js:8
1:51
    at compile (C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\webpack\lib\Compiler.js:222:
11)
    at hooks.afterCompile.callAsync.err (C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\web
pack\lib\Compiler.js:470:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Matt\Documents\dev\sweetalert2-react-conte
nt\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\Matt\Documents\dev\sweetalert2-react-content\n
ode_modules\tapable\lib\Hook.js:35:21)
    at compilation.seal.err (C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\webpack\lib\Com
piler.js:467:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Matt\Documents\dev\sweetalert2-react-conte
nt\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\Matt\Documents\dev\sweetalert2-react-content\n
ode_modules\tapable\lib\Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\w
ebpack\lib\Compilation.js:957:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Matt\Documents\dev\sweetalert2-react-conte
nt\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\Matt\Documents\dev\sweetalert2-react-content\n
ode_modules\tapable\lib\Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modu
les\webpack\lib\Compilation.js:948:32)
    at _err0 (eval at create (C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\tapable\lib\Ho
okCodeFactory.js:24:12), <anonymous>:11:1)
    at C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\uglifyjs-webpack-plugin\dist\index.js
:262:11
    at _class.runTasks (C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\uglifyjs-webpack-plu
gin\dist\uglify\index.js:63:9)
    at UglifyJsPlugin.optimizeFn (C:\Users\Matt\Documents\dev\sweetalert2-react-content\node_modules\uglifyjs-w
ebpack-plugin\dist\index.js:182:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sweetalert2-react-content@0.0.2 dev:sandbox: `webpack-serve sandbox/webpack.config.js --no-hot --no-re
load --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sweetalert2-react-content@0.0.2 dev:sandbox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matt\AppData\Roaming\npm-cache\_logs\2018-02-28T04_31_59_628Z-debug.log
```

**Comment by shellscape** [comment]
@zenflow yeah it looks like they aren't using the updated `html-webpack-plugin` that works with v4. OK, we'll get your patches in on another 0.1.x release so you can start using this. You're going to want to set your package.json dependency to `0.1.x` so you don't get the 0.2.0 release that drops webpack v3. You should follow up with that plugin's author/repo and report the v4 incompatibility in the meantime. I'll keep a branch for 0.1.x as well - in case any more blockers pop up we can publish a patch to 0.1.x.

**Comment by zenflow** [comment]
@shellscape 

> You should follow up with that plugin's author/repo and report the v4 incompatibility in the meantime.

Yeah, I'm happy to do this now that I've gotten a lot done towards some goals. First thing tomorrow I think.

Thank you so much! Keep up the great work!
