### ISSUE TITLE
webpack-serve doesn't work without entry in webpack.config.js

### ISSUE THREAD

**Issue by joshunger** [webpack-contrib/webpack-serve#39]
* Operating System: Darwin 17.4.0
* Node Version: 9.5.0
* NPM Version 5.6.0
* webpack Version 4.0.1
* webpack-server Version 0.1.5

This issue is for a:

- [x] **bug**
- [x] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve ./webpack.config.js
```

##### webpack.config.js

```js
const HtmlWebPackPlugin = require("html-webpack-plugin");

module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader",
            options: { minimize: true }
          }
        ]
      }
    ]
  },
  plugins: [
    new HtmlWebPackPlugin({
    })
  ]
};
```

### Expected Behavior
Works.

### Actual Behavior
Doesn't throw error immediately.  When Ctrl+C I see the following error
```
^CTypeError: webpack-hot-client: The value of `entry` must be an Array or Object. Please check your webpack config.
    at validateEntry (/Users/junger/dev/treefortschedule/frontend/node_modules/webpack-hot-client/lib/util.js:124:15)
    at module.exports (/Users/junger/dev/treefortschedule/frontend/node_modules/webpack-hot-client/index.js:32:3)
    at fn (/Users/junger/dev/treefortschedule/frontend/node_modules/koa-webpack/index.js:74:18)
    at middleware.webpack.state.getPort.then (/Users/junger/dev/treefortschedule/frontend/node_modules/webpack-serve/lib/server.js:32:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

I thought `entry` wasn't necessary?

**Comment by shellscape** [comment]
Thanks for the issue 🍺   This was already remedied and will be available in v0.2.0 when that's released this next week. That issue with not seeing the error was also squished and will be in the same release.
